### ISSUE TITLE
Change test/tests.yml

### ISSUE THREAD

**Issue by mjuenema** [mjuenema/cookiecutter-ansible-role#3]
- Remove `remote_user: root`.
- Add `connection: local`.

```
- hosts: localhost
  connection: local
  roles:
    - mjuenema.lxc
```

Also add note in README for testing:

```
( cd .. ; ansible-playbook --check -i mjuenema.lxc/tests/inventory mjuenema.lxc/tests/test.yml )
```
